---
  - name: Elk Installation
    hosts: elk
    remote_user: azadmin
    become: true
    tasks:

    - name: docker.io
      apt:
        force_apt_get: yes
        update_cache: yes
        name: docker.io
        state: present

    - name: Install python3-pip httpd (state=present is optional)
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    - name: Install Python Docker Module
      pip:
        name: docker
        state: present


    - name: Install data container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports:
         # Publish container port for Elasticsearch 9200
         - 9200:9200
         # Publish containter port for Logstash 5044
         - 5044:5044
         # Publish container port for Kibana 5601
         - 5601:5601

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
 
    - name: Increase virtual memory
      command: sysctl -w vm.max_map_count=262144

    - name: Use more memory
      sysctl:
       name: vm.max_map_count
       value: '262144'
       state: present
       reload: yes
